### ISSUE TITLE
The problem has been solved!

### ISSUE THREAD

**Issue by mousesmalltail** [zljkevin/ZLJBlockPrinter#1]

**Comment by zljkevin** [comment]
Type Encoding对照官网文档
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html

你怎么打印的，上代码我才知道

**Comment by zljkevin** [comment]
不要做伸手党，善用搜索引擎

**Comment by mousesmalltail** [comment]
我查出来是是BOOL，谢谢楼主哈
